#!/usr/bin/env bash
. ./scripts/theme || exit

# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK} you burped in her ear !${RESET}"
  " ${PINK} wa wa wee wa ♡${RESET}"
  " ${PINK} (>\\\<) *blushes*${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"