#!/usr/bin/env bash
. ./scripts/theme || exit
# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK} thanks owen :D${RESET}"
  " ${PINK} you're so sweet ♡${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"