#!/usr/bin/env bash
. ./scripts/theme || exit
# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK}she's been fed!${RESET}"
  " ${PINK}nom nom nom${RESET}"
  " ${PINK}she eated it all${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"