#!/usr/bin/env bash
. ./scripts/theme || exit
# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK} cooties!${RESET}"
  " ${PINK} arr arr arr arr${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"