#!/usr/bin/env bash
. ./scripts/theme || exit
# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK} you've tucked her in${RESET}"
  " ${PINK} honk mimimimi${RESET}"
  " ${PINK} *drools*${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"