#!/usr/bin/env bash
. ./scripts/theme || exit
# curl -X POST https://tanagotchi.mimobox.sh

messages=(
  " ${PINK} THIS GUY... HAS A BOMB!${RESET}"
  " ${PINK} *thumb war*${RESET}"
  " ${PINK} she is tickling you (gently)${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"